netid = 123
notransit = false
floodfill = false
bandwidth = X

ipv4 = true
ipv6 = false
nat = false
ifname4 = lo0

address4 = 127.0.0.1
host = 127.0.0.1
reservedrange = false

[ntcp2]
enabled   = true
port 	  = 4568
published = true

[reseed]
verify = false
urls   =
threshold = 0
floodfill = /tmp/i2pd-ff/router.info

[trust]
enabled = false

[exploratory]
inbound.length=0
outbound.length=0
inbound.quantity=1
outbound.quantity=1

[addressbook]
enabled = false

[ssu2]
enabled = false

[socksproxy]
enabled = false

[http]
enabled = false

[httpproxy]
enabled=false

[sam]
enabled = false
