## Local-only, no public Internet
netid = 123
notransit = false
floodfill = true
bandwidth = X             # no limit, or K if you want minimal

## Bind only to loopback
ipv4 = true
ipv6 = false
nat = false
ifname4 = lo0

address4 = 127.0.0.1
host = 127.0.0.1
reservedrange = false

[ntcp2]
enabled   = true
port      = 4570
published = true

[reseed] # No public reseed
verify = false
urls =
file =
zipfile =
threshold = 0

[exploratory]
inbound.length=0
outbound.length=0
inbound.quantity=0
outbound.quantity=0

[addressbook]
enabled = false

[ssu2]
enabled   = false

[socksproxy]
enabled = false

[http]
enabled=true
address = 127.0.0.1
port = 7070
auth = false

[httpproxy]
enabled=false

[sam]
enabled=false